# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20170208_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateField(help_text='dd/mm/yy', null=True, verbose_name='Date: '),
        ),
    ]
