# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_training_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='planned_type_of_training',
            field=models.CharField(max_length=20, null=True, verbose_name='Planned type of training: '),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(help_text='dd/mm/yyyy', null=True, verbose_name='Date: '),
        ),
    ]
