# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20160727_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='average_heart_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='in_zone',
            field=models.DurationField(),
        ),
    ]
