# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20170213_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='notes',
            field=models.CharField(max_length=70, null=True, verbose_name='Notes: '),
        ),
    ]
