# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_training_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField(help_text='1', verbose_name='Zone: ')),
                ('upper_heart_rate', models.IntegerField(help_text='145', null=True, verbose_name='Upper heart rate: ')),
                ('lower_heart_rate', models.IntegerField(help_text='155', null=True, verbose_name='Lower heart rate: ')),
            ],
        ),
    ]
