# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-23 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_trainingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtype',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Description: '),
        ),
    ]
