# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_trainingtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='planned_type_of_training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.TrainingType'),
        ),
    ]
